name: CI

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          
      - name: Update README
        run: |
          echo " " >> README.md
          git add README.md
          git commit -m "Trade data is ready!"
          git push origin HEAD:master
