name: CI

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

permissions:
  contents: write  # This is needed for pushing commits

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Trade detail
        run: |
          echo " " >> README.md
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          git add .
          git commit -m "New trade detail is here!"
          git push
