name: CI

on:
  schedule:
    - cron: "30 8 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo "${{ github.ref }} -> README.md"
      
    - name: Commit changes
      run: |
        git config user.name '((owoeye-babatunde))'
        git config user.email '((babatundeowoeye7@gmail.com))'
        git add .
        git commit -m "Trade data is here!"
        git push
